envs:
  cartpole:
    name: CartPole-v0
    num_actions: 2
    state_space: 4
    max_episodes: 500
    win_condition:
      score: 195
      over: 100
  cartpole_v1:
    name: CartPole-v1
    num_actions: 2
    state_space: 4
    max_episodes: 600
    win_condition:
      score: 495
      over: 100
  mountaincar:
    name: MountainCar-v0
    num_actions: 3
    state_space: 2
    max_episodes: 20000
    win_condition:
      score: -110
      over: 100
  lunar:
    name: LunarLander-v2
    num_actions: 4
    state_space: 8
    max_episodes: 50000
    win_condition:
      score: 200
      over: 100
  pong:
    name: Pong-v0
    num_actions: 6
    state_space: 6400
    max_episodes: 50000
    win_condition:
      score: 17
      over: 10
  pendulum:
    name: Pendulum-v0
    num_actions: 1
    state_space: 3
    max_episodes: 5000
    win_condition:
      score: -150
      over: 100

general:
  test: False
  active_agent: actor_critic
  active_env: lunar
  use_win_condition: True
  time: True
  load: False

algorithms:
  dqn:
    gamma: .99
    learning_rate: 0.001
    max_memory_size: 50000
    batch_size: 32
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.999
    cartpole:
      gamma: 1
      max_memory_size: 30000
      epsilon_decay: 0.99
    mountaincar:
      max_memory_size: 10000
  policy:
    learning_rate: 0.01
    gamma: 1.
    batch_size: 20
    cartpole:
      gamma: 1
      learning_rate: 0.1
    lunar:
      gamma: .99
      learning_rate: 0.001
  actor_critic:
    gamma: .99
    actor_lr: 0.001
    critic_lr: 0.005
    max_memory_size: 5000
    batch_size: 32
    mountaincar:
      max_memory_size: 10000
    lunar:
      max_memory_size: 50000
  atari-dqn:
    gamma: .99
    learning_rate: 0.001
    batch_size: 32
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.9999
    max_memory_size: 500000
  atari-policy:
    learning_rate: 0.001
    gamma: .99
    batch_size: 10
  pg-continuous:
    learning_rate: 0.001
    gamma: .99
    batch_size: 10
  ac-continuous:
    gamma: .99
    actor_lr: 0.001
    critic_lr: 0.005
    max_memory_size: 10000
    batch_size: 32
  random:

test:
  use_win_condition: False
  envs:
#    - cartpole
#    - mountaincar
    - lunar
#    - pong
#    - pendulum
  methods:
#    - dqn
    - actor_critic
#    - policy
#    - random
#    - atari-policy
#    - ac-continuous
#    - pg-continuous
  number: 1

log:
  average: 100
  log_every: 10
  log_avg_every: 100
