envs:
  cartpole:
    name: CartPole-v0
    num_actions: 2
    state_space: 4
    max_episodes: 400
    win_condition:
      score: 195
      over: 100
  mountaincar:
    name: MountainCar-v0
    num_actions: 3
    state_space: 2
    max_episodes: 1000
    win_condition:
      score: -100
      over: 100

general:
  test: True
  active_agent: policy
  active_env: cartpole
  use_win_condition: False

algorithms:
  dqn:
    gamma: 1
    learning_rate: 0.001
    max_memory_size: 5000
    batch_size: 32
    epsilon_start: 1
    epsilon_end: 0.05
    epsilon_decay: 0.99
  policy:
    learning_rate: 0.1
  actor_critic:
    learning_rate: 0.1

test:
  use_win_condition: False
  envs:
    - cartpole
    - mountaincar
  methods:
    - dqn
    - policy
    - actor_critic
  number: 5
